source     : .
destination: ./_site
plugins    : ./_plugins

future   : false
lsi      : false
pygments : true
markdown : maruku
permalink: /:title.html
paginate : 5
tweets   : 5
contact  : http://leonardothibes.com/ws/contact-form

author:
    me:
        name     : Leonardo Thibes
        gravatar : 2fba7f857adaa92a56c7163b68ba420d
        email    : eu@leonardothibes.com
        twitter  : leonardothibes
        facebook : leonardothibes
        github   : leonardothibes
        youtube  : lthibes
        linkedin : leonardo-castilhos-thibes/29/a0/33b

projects-list:
    - id: fakeseguro
    - id: zf
    - id: php-skel
    - id: puppet-web
    - id: puppet-workstation

projects:
    fakeseguro:
        name: Fake Seguro
        desc: Gateway de pagamento para testes de integração com o PagSeguro do UOL. 
              Ainda em estágio embrionário, mas funcional.
        link: https://github.com/leonardothibes/fakeseguro#readme
    zf:
        name: Esqueleto de projeto em Zend Framework
        desc: Um projeto básico implementado em PHP5 e Zend Framework já configurado 
              para as minhas necessidades mais comuns, e contendo as bibliotecas que
              mais uso no dia-a-dia.
        link: https://github.com/leonardothibes/zf#readme
    php-skel:
        name: PHP-Skel
        desc: Um esqueleto projeto implementado em PHP5.3 já configurado com testes unitários(PHPUnit),
              verificação de padrão de código(Code-Sniffer) e integração contínua+deploy(Phing).
        link: https://github.com/leonardothibes/php-skel#readme
    puppet-web:
        name: Puppet Web
        desc: Servidor web compatível tanto com RedHat/CentOS quanto com Debian/Ubuntu.
        link: https://github.com/leonardothibes/puppet-web#readme
    puppet-workstation:
        name: Puppet Workstation
        desc: Estação de trabalho para desenvolvimento web em PHP.
        link: https://github.com/leonardothibes/puppet-workstation#readme

portfolio-list:
    - id: telesena
    - id: lidercap
    - id: bau
    - id: jacotei
    - id: epoc-events
    - id: fmc-arquitetura

portfolio:
    telesena:
        link  : http://www.telesena.com.br
        name  : Site Tele Sena
        client: Liderança Capitalização S.A.
        cdesc : Uma empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    lidercap:
        link  : http://www.lidercap.com.br
        name  : Site Liderança Capitalização
        client: Liderança Capitalização S.A.
        cdesc : Uma empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    bau:
        link  : http://www.bau.com.br
        name  : Site Baú da Felicidade
        client: Baú da Felicidade
        cdesc : Uma empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    jacotei:
        link  : http://www.jacotei.com.br
        name  : Site Já Cotei - Cotação e Comparação de Preços
        client: DND
        cdesc : Desenvolvimento de Negócios Digitais
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    epoc-events:
        link  : http://www.oztechnology.com.br/produtos/e-poc-events
        name  : E-POC Events - Sistema de gerenciamento de casas noturnas e eventos pré-pagos
        client: OZ Technology
        cdesc : Softwares de gestão para eventos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    fmc-arquitetura:
        link  : http://www.fmc-arquitetura.com.br
        name  : Site FMC Arquitetura
        client: FMC Arquitetura
        cdesc : Ferrés, Milani & Campanhã
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.

sites-we-watch:
    - url: "http://macmagazine.com.br"
    - url: "http://br-mac.org"
    - url: "http://br-linux.org"
    - url: "http://efetividade.net"
    - url: "http://itechhoje.com.br"
    - url: "http://happyhourtech.com"
    - url: "http://applespotlight.com.br"
    - url: "http://blogappleforfuture.com.br"
    - url: "http://carreirasolo.org"
    - url: "http://webappers.com"
    - url: "http://akitaonrails.com"
    - url: "http://lornlab.org"
    - url: "http://ajaxianos.com.br"
    - url: "http://tableless.com.br"
    - url: "http://addyosmani.com"
    - url: "http://zenorocha.com"
    - url: "http://apssouza.com.br"
    - url: "http://blog.stancke.com.br"
    - url: "http://blog.naenius.com"
    - url: "http://abstraindo.com"
