source     : .
destination: ./_site
plugins    : ./_plugins

future   : false
lsi      : false
pygments : true
markdown : maruku
permalink: /:title.html
paginate : 5
tweets   : 5

author:
    me:
        name     : Leonardo Thibes
        gravatar : 2fba7f857adaa92a56c7163b68ba420d
        email    : eu@leonardothibes.com
        twitter  : leonardothibes
        facebook : leonardothibes
        github   : leonardothibes
        youtube  : lthibes
        linkedin : leonardo-castilhos-thibes/29/a0/33b

projects-list:
    - id: fakeseguro
    - id: puppet-web
    - id: puppet-workstation

projects:
    fakeseguro:
        name: Fake Seguro
        desc: Gateway de pagamento para testes de integração com o PagSeguro do UOL. 
              Ainda em estágio embrionário.
        link: https://github.com/leonardothibes/fakeseguro#readme
    puppet-web:
        name: Puppet Web
        desc: Servidor web compatível tanto com RedHat/CentOS quanto com Debian/Ubuntu.
        link: https://github.com/leonardothibes/puppet-web#readme
    puppet-workstation:
        name: Puppet Workstation
        desc: Estação de trabalho para desenvolvimento web em PHP.
        link: https://github.com/leonardothibes/puppet-workstation#readme

portfolio-list:
    - id: telesena
    - id: lidercap
    - id: bau
    - id: jacotei
    - id: epoc-events

portfolio:
    telesena:
        url   : http://www.telesena.com.br
        name  : Site Tele Sena
        client: Liderança Capitalização
        cdesc : Um empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    lidercap:
        url   : http://www.lidercap.com.br
        name  : Site Liderança Capitalização
        client: Liderança Capitalização
        cdesc : Um empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    bau:
        url   : http://www.bau.com.br
        name  : Site Baú da Felicidade
        client: Baú da Felicidade
        cdesc : Um empresa do Grupo Sílvio Santos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    jacotei:
        url   : http://www.bau.com.br
        name  : Site Já Cotei - Cotação e Comparação de Preços
        client: DND
        cdesc : Desenvolvimento de Negócios Digitais
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.
    epoc-events:
        url   : http://www.oztechnology.com.br/produtos/e-poc-events
        name  : E-POC Events - Sistema de gerenciamento de casas noturnas e raves
        client: OZ Technology
        cdesc : Softwares de gestão para eventos
        text  : Pellentesque habitant morbi tristique senectus et netus et malesuada fames, Pellentesque 
                habitant morbi tristique senectus et netus et malesuada fames Pellentesque habitant morbi 
                tristique senectus et netus et malesuada fames, Pellentesque habitant morbi tristique senectus 
                et netus et malesuada fames, Pellentesque habitant morbi fames.

sites-we-watch:
    - url: "http://macmagazine.com.br"
    - url: "http://br-mac.org"
    - url: "http://br-linux.org"
    - url: "http://efetividade.net"
    - url: "http://itechhoje.com.br"
    - url: "http://carreirasolo.org"
    - url: "http://webappers.com"
    - url: "http://akitaonrails.com"
    - url: "http://lornlab.org"
    - url: "http://ajaxianos.com.br"
    - url: "http://tableless.com.br"
    - url: "http://addyosmani.com"
    - url: "http://zenorocha.com"
    - url: "http://apssouza.com.br"
