source     : .
destination: ./_site
plugins    : ./_plugins

future   : false
lsi      : false
pygments : true
markdown : maruku
permalink: /:title.html

author:
    me:
        name     : Leonardo Thibes
        gravatar : 2fba7f857adaa92a56c7163b68ba420d
        email    : eu@leonardothibes.com
        twitter  : leonardothibes
        facebook : leonardothibes
        github   : leonardothibes

sites-we-watch:
    - url: "http://efetividade.net"
    - url: "http://br-linux.org"
    - url: "http://br-mac.org"
    - url: "http://macmagazine.com.br"
    - url: "http://itechhoje.com.br"
    - url: "http://carreirasolo.org"