source     : .
destination: ./_site
plugins    : ./_plugins

future   : false
lsi      : false
pygments : true
markdown : maruku
permalink: /:title.html
paginate : 5

post:
    img-dir: /public/img/posts

last-tweets:
    username: leonardothibes
    limit   : 5

author:
    me:
        name     : Leonardo Thibes
        gravatar : 2fba7f857adaa92a56c7163b68ba420d
        email    : eu@leonardothibes.com
        twitter  : leonardothibes
        facebook : leonardothibes
        github   : leonardothibes
        youtube  : lthibes
        linkedin : leonardo-castilhos-thibes/29/a0/33b

sites-we-watch:
    - url: "http://macmagazine.com.br"
    - url: "http://br-linux.org"
    - url: "http://br-mac.org"
    - url: "http://efetividade.net"
    - url: "http://itechhoje.com.br"
    - url: "http://carreirasolo.org"
    - url: "http://webappers.com"
    - url: "http://akitaonrails.com"
    - url: "http://lornlab.org"
    - url: "http://ajaxianos.com.br"
    - url: "http://tableless.com.br"
    - url: "http://addyosmani.com"
    - url: "http://zenorocha.com"
