source     : .
destination: ./_site
plugins    : ./_plugins

future   : false
lsi      : false
pygments : true
markdown : maruku
permalink: /:title.html
paginate : 5
tweets   : 5

post:
    img-dir: /public/img/posts

author:
    me:
        name     : Leonardo Thibes
        gravatar : 2fba7f857adaa92a56c7163b68ba420d
        email    : eu@leonardothibes.com
        twitter  : leonardothibes
        facebook : leonardothibes
        github   : leonardothibes
        youtube  : lthibes
        linkedin : leonardo-castilhos-thibes/29/a0/33b

projects:
    - id: fakeseguro
    - id: puppet-web
    - id: puppet-workstation

projects-list:
    fakeseguro:
        name: Fake Seguro
        desc: Gateway de pagamento para testes de integração com o PagSeguro do UOL.
        link: https://github.com/leonardothibes/fakeseguro
    puppet-web:
        name: Puppet Web
        desc: Servidor web compatível tanto com RedHat/CentOS quanto com Debian/Ubuntu.
        link: https://github.com/leonardothibes/puppet-web
    puppet-workstation:
        name: Puppet Workstation
        desc: Estação de trabalho para desenvolvimento web em PHP.
        link: https://github.com/leonardothibes/puppet-workstation

sites-we-watch:
    - url: "http://macmagazine.com.br"
    - url: "http://br-linux.org"
    - url: "http://br-mac.org"
    - url: "http://efetividade.net"
    - url: "http://itechhoje.com.br"
    - url: "http://carreirasolo.org"
    - url: "http://webappers.com"
    - url: "http://akitaonrails.com"
    - url: "http://lornlab.org"
    - url: "http://ajaxianos.com.br"
    - url: "http://tableless.com.br"
    - url: "http://addyosmani.com"
    - url: "http://zenorocha.com"
